detectors:
  IrresponsibleModule:
    enabled: false

  UncommunicativeModuleName:
    enabled: false

  NestedIterators:
    enabled: false

  FeatureEnvy:
    enabled: false

exclude_paths:
  - db/
