default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: planner-api-development

test:
  <<: *default
  database: planner-api-test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV.fetch('DB_NAME', 'planner-api') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>
